// Generated by CoffeeScript 1.4.0
/*

  Player.js

  2013 (c) Andrey Popp <8mayday@gmail.com>
*/

var PlayerJS, YoutubeSound, injectYT, isYouTubeRe;

injectYT = function() {
  var firstScriptTag, tag;
  tag = document.createElement('script');
  if (window.location.host === 'localhost') {
    tag.src = "http://www.youtube.com/player_api";
  } else {
    tag.src = "//www.youtube.com/player_api";
  }
  firstScriptTag = document.getElementsByTagName('script')[0];
  return firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
};

/*
  This class mimics soundManager2's Sound.
*/


YoutubeSound = (function() {
  var extractIdRe;

  extractIdRe = /v=([^&]+)/;

  function YoutubeSound(options) {
    var videoId,
      _this = this;
    this.options = options;
    videoId = options.youtubeVideoId || extractIdRe.exec(options.url)[1];
    if (!(videoId != null)) {
      throw new Error("cannot extract videoId from URL: " + options.url);
    }
    this.player = new YT.Player(options.playerId, {
      height: options.height,
      width: options.width,
      videoId: videoId,
      events: {
        onReady: function() {
          return console.log('ready');
        },
        onStateChange: function() {
          return console.log('statechange');
        }
      },
      playerVars: {
        controls: '0',
        enablejsapi: '1',
        modestbranding: '1',
        showinfo: '0',
        playerapiid: options.id
      }
    });
  }

  YoutubeSound.prototype.onReady = function() {
    return console.log('ready');
  };

  YoutubeSound.prototype.onStateChange = function() {
    return console.log('statechange');
  };

  YoutubeSound.prototype.destruct = function() {
    return this.player.destroy();
  };

  YoutubeSound.prototype.load = function() {};

  YoutubeSound.prototype.clearOnPosition = function() {};

  YoutubeSound.prototype.onPosition = function() {};

  YoutubeSound.prototype.mute = function() {
    return this.player.mute();
  };

  YoutubeSound.prototype.pause = function() {
    return this.player.pauseVideo();
  };

  YoutubeSound.prototype.play = function() {
    return this.player.playVideo();
  };

  YoutubeSound.prototype.resume = function() {
    return this.play();
  };

  YoutubeSound.prototype.setPan = function() {};

  YoutubeSound.prototype.setPosition = function(ms) {
    return this.player.seekTo(ms / 1000);
  };

  YoutubeSound.prototype.setVolume = function(v) {
    return this.player.setVolume(v);
  };

  YoutubeSound.prototype.stop = function() {
    return this.player.stopVideo();
  };

  YoutubeSound.prototype.toggleMute = function() {
    if (this.player.isMuted()) {
      return this.unmute();
    } else {
      return this.mute();
    }
  };

  YoutubeSound.prototype.togglePause = function() {
    if (this.player.getPlayerState() === YT.PlayerState.PLAYING) {
      return this.pause();
    } else {
      return this.play();
    }
  };

  YoutubeSound.prototype.unload = function() {};

  YoutubeSound.prototype.unmute = function() {
    return this.player.unMute();
  };

  return YoutubeSound;

})();

isYouTubeRe = /youtube.com/;

PlayerJS = {
  createSound: function(options) {
    if (isYouTubeRe.test(options.url)) {
      return new YoutubeSound(options);
    } else {
      return soundManager.createSound(options);
    }
  }
};
